# Elasticsearch with exposed port and custom heap size
elasticsearch:
  image: elasticsearch:2.0.0
  command:
    - "elasticsearch"
    - "--network.host"
    - "0.0.0.0"
  environment:
    ES_HEAP_SIZE: 1G
  ports:
    - "9200:9200"    

logstash:
  build: logstash
  links:
    - elasticsearch
  volumes:
    - ./logs:/logs

# Kibana index initializer
kibana-config:
  build: kibana-config
  links:
    - elasticsearch

# Kibana with modified entry point to wait for index initialization
kibana:
  build: kibana
  links:
    - elasticsearch
  ports:
    - "5601:5601"

# Host oncrawl-elk UI
nginx:
  image: nginx:1.9.6
  ports:
    - "9000:80"
  volumes:
    - ./nginx/html:/usr/share/nginx/html:ro
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf